<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => "Professor Dr. A.Q.M. Mahbub",
                "password"=>bcrypt("11"),
                "department_id" => null,
                "room_id" => 2,
                "designation" => "Vice Chancellor, BSMRSTU",
                "website" => "www.dummydata.com",
                "phone" => "0000000000",
                "email" => "dummydata@gmail.com",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Professor Dr. Md. Abdul Rohim Khan",
                "password"=>bcrypt("11"),
                "designation" => "Professor",
                "department_id" => 7,
                "room_id" => 3,
                "phone" => "dummy data",
                "email" => "dummydata1@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Dr. Saleh Ahmed",
                "password"=>bcrypt("11"),
                "designation" => "Associate Professor",
                "department_id" => "1",
                "room_id" => 16,
                "phone" => "dummy data",
                "email" => "dummydata2@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Professor Dr. N.A Sattar",
                "password"=>bcrypt("11"),
                "designation" => "Professor",
                "department_id" => "12",
                "room_id" => 8,
                "phone" => "dummy data",
                "email" => "dummydata3@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Dr. Mojahar Ali",
                "password"=>bcrypt("11"),
                "designation" => "Professor",
                "department_id" => "31",
                "room_id" => 4,
                "phone" => "dummy data",
                "email" => "dummydata4@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Dr. Mrinal Kanti Baowaly",
                "password"=>bcrypt("11"),
                "designation" => "Associate Professor",
                "department_id" => "1",
                "room_id" => 13,
                "phone" => "+8801913912066",
                "email" => "baowaly@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Md. Jamal Uddin",
                "password"=>bcrypt("11"),
                "designation" => "Assistant Professor",
                "department_id" => "1",
                "room_id" => 18,
                "phone" => "+8801734-531900",
                "email" => "jamal.bsmrstu@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Md. Nesarul Hoque",
                "password"=>bcrypt("11"),
                "designation" => "Assistant Professor",
                "department_id" => "1",
                "room_id" => 18,
                "phone" => "+8801712-820727",
                "email" => "mnhshisir@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Rabiul Islam",
                "password"=>bcrypt("11"),
                "designation" => "Assistant Professor",
                "department_id" => "26",
                "room_id" => 7,
                "phone" => "01712944031",
                "email" => "rabiul.islam75@yahoo.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Dr. Md. Abdullah Al Asad",
                "password"=>bcrypt("11"),
                "designation" => "Associate Professor",
                "department_id" => "2",
                "room_id" => 6,
                "phone" => "01712944031",
                "email" => "abdullah Al Asad@yahoo.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Shihab Ahammed",
                "password"=>bcrypt("11"),
                "designation" => "Associate Professor",
                "department_id" => "2",
                "room_id" => 12,
                "phone" => "8801813127037",
                "email" => "shihabahammed4979@yahoo.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Md. Faykuzzaman Mia",
                "password"=>bcrypt("11"),
                "designation" => "Assistant Professor",
                "department_id" => "2",
                "room_id" => 5,
                "phone" => "01722000165",
                "email" => "fzaman.ru@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
            [
                'name' => "Mr X.",
                "password"=>bcrypt("11"),
                "designation" => "Assistant Professor",
                "department_id" => "2",
                "room_id" => 5,
                "phone" => "23456789",
                "email" => "x@gmail.com",
                "website" => "dummy data",
                "biographyFiledOfSpecialization" => "dummy data",
                "researchInterest" => "dummy data",
                "currentResearchAndCollaboration" => "dummy data",
                "fellowshipOfScientificAndProfessionalSociaties" => "dummy data",
                "journals"=>"dummy data",
                "awardAndRecognition" => "dummy data",
                "publication" => "dummy data",
                "conference" => "dummy data",
                "graduateSupervision" => "dummy data",
                "courseOffered" => "dummy data",
                "courseMaterial" => "dummy data",
                "teachingExperience" => "dummy data",
                "educationExperience" => "dummy data",
                "researchExperience" => "dummy data"
            ],
        ]);
    }
}
